apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-coordinator
  namespace: {{ .Release.Namespace }}
  labels:
    app: dremio
    role: coordinator
spec:
  clusterIP: None
  ports:
    - port: 9047
      name: web
    - port: 31010
      name: jdbc
    - port: 32010
      name: flight
    - port: 45678
      name: inter-node
    - port: 2181
      name: zookeeper
  selector:
    app: dremio
    role: coordinator
