apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dremio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: 9047
      name: web
    - port: {{ .Values.service.flightPort }}
      targetPort: 32010
      name: flight
    - port: {{ .Values.service.jdbcPort }}
      targetPort: 31010
      name: jdbc
  selector:
    app: dremio
    role: coordinator
