apiVersion: v1
kind: Namespace
metadata:
  name: data-infra
  labels:
    platform: napas
    layer: "00-infra"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-security
  labels:
    platform: napas
    layer: "01-security"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-storage
  labels:
    platform: napas
    layer: "02-storage"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-ingestion
  labels:
    platform: napas
    layer: "03-ingestion"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-governance
  labels:
    platform: napas
    layer: "04-governance"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-processing
  labels:
    platform: napas
    layer: "05-processing"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-visualization
  labels:
    platform: napas
    layer: "06-visualization"
